language: go

go:
  - 1.8.x
  - 1.9.x

install:#依赖安装
  - go get github.com/go-playground/overalls #overalls能够支持到各级子目录
  - go get github.com/mattn/goveralls #goveralls是coveralls对golang的测试覆盖率支持命令
  - go get github.com/smartystreets/goconvey#很好用的测试工具
  - mkdir -p $GOPATH/src/github.com/red-chen
  - cd $GOPATH/src/github.com/red-chen/goargs

script:# 集成脚本
    - overalls -project=github.com/red-chen/goargs -covermode=count -ignore='.git,_vendor'
    - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
    - go test -race -coverprofile=coverage.txt -covermode=atomic # 注意要添加这一行，否则不会出现 codecov bot
    - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "XDJzjITvTLkdZ4jVFbNY6pFs4u+5OhZDFFbXEhTbxrDeCTmneVdxUzZA2iz5QICOQUhJR4gMKIkLFsb3/iFwtK07Zd43m4i8cKjNQNkTzC6pXYYmZt8WpVDsIqBzTDYns/Rn9Ys0T4kdFcFm+0vnyobD2YJ3aeIectDh2pU9F5hjQz9R2U3xVfpGaxGoU8n9gtRqQuHgNUDD8F92u/AAki/YpUM7d+eOUz0mxjSMjST7e1gETphHRbolc0TwNT+Q/734aC/mYKtc16x4OH8bR5wy3yz5DCoKK0Q+3zCYZGthbFD0FxHwUwyHDsOkEIUBYkXcatXfzdXYlQr1AKPYJaWoE3bSVaC7Bmzy/NQ0U0BULtain9eNEyCQ58BBCvuMo+x27rDU3Wx7LXcjCsNbfwc5gdSJYYTUjwhO1e2O6edP8bKBl+m4LB8AtJjSwzCIyLT7YJtjwCNYvFlY46bxFuqDdDwURi/M/Z0Zw+4fwJkkYoP/HBOYBNEWih600p5FDf1lsiYUEtfAdjjbbB3qstVAX1k1t3onmbBBNpxgp+CrvwoDnwXytmDsI3uWyyl5PwODsyVRUhZaE9pSdi+PZA6CtX/Bd0IRdXYUx0TdufZ18iATgfjoLrAlCwE5PcDMvVTaHaxXi4H1qmqbBrqBpWSMjfM6EqIscB6lxTZMJ5E="
